In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

warnings.filterwarnings('ignore')
df = pd.read_csv('Clustering_Data.csv')
df.head(4)

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       0  21.0    1.62    64.0                               1     0   2.0   
1       0  21.0    1.52    56.0                               1     0   3.0   
2       1  23.0    1.80    77.0                               1     0   2.0   
3       1  27.0    1.80    87.0                               0     0   3.0   
4       1  22.0    1.78    89.8                               0     0   2.0   

   NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  NObeyesdad  
0  3.0     2      0   2.0    0  0.0  1.0     3       3           1  
1  3.0     2      1   3.0    1  3.0  0.0     2       3           1  
2  3.0     2      0   2.0    0  2.0  1.0     1       3           1  
3  3.0     2      0   2.0    0  2.0  0.0     1       4           5  
4  1.0     2      0   2.0    0  0.0  0.0     2       3           6

In [129]:
df

Gender        Age    Height     Weight  family_history_with_overweight  \
0          1  29.216019  1.752265  88.096062                               1   
1          0  43.238402  1.733875  86.945380                               1   
2          0  23.000000  1.590000  48.000000                               1   
3          1  29.000000  1.682916  89.991671                               1   
4          1  21.033794  1.625891  70.000000                               0   
...      ...        ...       ...        ...                             ...   
1495       1  23.000000  1.770000  60.000000                               1   
1496       0  32.000000  1.670000  90.000000                               1   
1497       1  18.000000  1.760000  70.000000                               1   
1498       0  40.000000  1.550000  62.000000                               1   
1499       1  30.079371  1.810616  92.860254                               1   

      FAVC      FCVC       NCP  CAEC  SMOKE      CH2O  SCC       FAF  \
0        1  2.000000  1.894384     2      0  2.000000    0  0.000000   
1        1  2.353603  2.337035     2      0  1.830614    0  0.706287   
2        1  2.000000  1.000000     1      0  1.000000    0  0.000000   
3        1  1.851262  3.000000     2      0  2.112670    0  0.388269   
4        1  2.000000  1.000000     3      0  2.008760    0  0.631190   
...    ...       ...       ...   ...    ...       ...  ...       ...   
1495     1  3.000000  1.000000     2      0  1.000000    0  1.000000   
1496     1  3.000000  1.000000     2      0  2.000000    0  2.000000   
1497     1  2.000000  4.000000     1      0  2.000000    0  2.000000   
1498     0  3.000000  3.000000     2      0  3.000000    0  0.000000   
1499     1  2.000000  3.000000     2      0  1.622638    0  0.033745   

           TUE  CALC  MTRANS  NObeyesdad  labels  
0     0.000000     2       3           6       1  
1     0.000000     3       0           6       3  
2     2.000000     2       3           1       0  
3     0.000000     2       0           2       3  
4     0.000000     2       3           5       1  
...        ...   ...     ...         ...     ...  
1495  1.000000     2       3           1       1  
1496  0.000000     2       0           2       3  
1497  1.000000     2       0           1       1  
1498  0.000000     2       0           5       3  
1499  0.105895     2       3           6       1  

[1500 rows x 18 columns]

In [12]:
scaler = StandardScaler()   
scaled_df = scaler.fit_transform(df)

kmeans = KMeans(n_clusters=4)

kmeans.fit(scaled_df)

print(kmeans.cluster_centers_)

[[-6.35266529e-01 -4.15109302e-01 -5.88920248e-01 -8.53224890e-01
  -6.53097110e-01 -3.13255804e-01  1.09190551e-01 -6.23782459e-04
  -5.24147862e-01  3.09573391e-02 -4.58459468e-01 -2.61488180e-01
  -8.71867491e-02  6.82727281e-02  2.20527992e-01  4.85824881e-01
  -6.35851262e-01]
 [ 5.73233806e-01 -3.49964258e-01  5.43893321e-01  4.97208445e-01
   4.00583146e-01  2.42590736e-01 -2.11080433e-01  6.28991876e-02
   3.40844618e-01 -8.48219563e-02  3.64265239e-01 -2.61488180e-01
   9.86500453e-02  2.11667908e-01 -7.53788489e-02  3.28986225e-01
   2.54396742e-01]
 [-5.04588202e-01 -4.24886877e-01 -5.00683531e-01 -6.52171747e-01
  -5.93238189e-01 -6.45947825e-01  5.86025432e-01  2.24386141e-02
  -3.51069306e-01  1.43757360e-01  6.36011853e-02  3.82426464e+00
   2.46177090e-01 -9.36937383e-02 -9.17599788e-02  2.61827006e-01
  -1.17098959e-01]
 [-1.27500828e-01  1.66565037e+00 -1.36561414e-01  4.66133003e-01
   3.41442025e-01  1.67299339e-01  1.18559655e-01 -1.55619973e-01
   1.85598735e-01  

In [13]:
centroids = kmeans.cluster_centers_

In [14]:
centroids[3]

array([-0.12750083,  1.66565037, -0.13656141,  0.466133  ,  0.34144202,
        0.16729934,  0.11855965, -0.15561997,  0.18559874,  0.10041291,
       -0.12056553, -0.2468439 , -0.17223177, -0.58336344, -0.15771649,
       -1.67828685,  0.49691395])

In [15]:
print(kmeans.labels_)

[0 2 1 ... 1 0 3]


In [16]:
df['labels'] = kmeans.labels_
df.head(4)

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       0  21.0    1.62    64.0                               1     0   2.0   
1       0  21.0    1.52    56.0                               1     0   3.0   
2       1  23.0    1.80    77.0                               1     0   2.0   
3       1  27.0    1.80    87.0                               0     0   3.0   
4       1  22.0    1.78    89.8                               0     0   2.0   

   NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  NObeyesdad  labels  
0  3.0     2      0   2.0    0  0.0  1.0     3       3           1       0  
1  3.0     2      1   3.0    1  3.0  0.0     2       3           1       2  
2  3.0     2      0   2.0    0  2.0  1.0     1       3           1       1  
3  3.0     2      0   2.0    0  2.0  0.0     1       4           5       1  
4  1.0     2      0   2.0    0  0.0  0.0     2       3           6       1

In [22]:
df = df.sample(frac=1).reset_index(drop=True)
df.head(4)

Gender        Age    Height     Weight  family_history_with_overweight  \
0       1  29.216019  1.752265  88.096062                               1   
1       0  43.238402  1.733875  86.945380                               1   
2       0  23.000000  1.590000  48.000000                               1   
3       1  29.000000  1.682916  89.991671                               1   
4       1  21.033794  1.625891  70.000000                               0   

   FAVC      FCVC       NCP  CAEC  SMOKE      CH2O  SCC       FAF  TUE  CALC  \
0     1  2.000000  1.894384     2      0  2.000000    0  0.000000  0.0     2   
1     1  2.353603  2.337035     2      0  1.830614    0  0.706287  0.0     3   
2     1  2.000000  1.000000     1      0  1.000000    0  0.000000  2.0     2   
3     1  1.851262  3.000000     2      0  2.112670    0  0.388269  0.0     2   
4     1  2.000000  1.000000     3      0  2.008760    0  0.631190  0.0     2   

   MTRANS  NObeyesdad  labels  
0       3           6       1  
1       0           6       3  
2       3           1       0  
3       0           2       3  
4       3           5       1

In [110]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=0.3)

train_x = train.drop('labels', axis=1)
train_y = train['labels']

test_x = test.drop('labels', axis=1)
test_y = test['labels']

In [111]:
knn_clf = KNeighborsClassifier(n_neighbors=7, metric='euclidean')

knn_clf.fit(train_x, train_y)

KNeighborsClassifier(metric='euclidean', n_neighbors=7)

In [112]:
pred = knn_clf.predict(test_x)

In [113]:
from sklearn.metrics import accuracy_score

print("Accuracy of the classifier:", accuracy_score(test_y, pred))

Accuracy: 0.8866666666666667


In [ ]:
df2 = pd.read_csv('Classification_Data.csv')
df2.head(4)

In [117]:
pred2 = knn_clf.predict(df2)

In [119]:
pred2.shape

(611,)

In [122]:
df2['labels'] = pred2
df2.head(7)

Gender        Age    Height      Weight  family_history_with_overweight  \
0       1  21.721507  1.849998  122.119682                               1   
1       1  18.880610  1.804160  104.406820                               1   
2       0  25.907833  1.623113  102.555691                               1   
3       0  25.934757  1.579893  102.134646                               1   
4       0  23.664709  1.738836  133.472641                               1   
5       1  31.490699  1.773521  120.209711                               1   
6       1  24.417552  1.774775  117.398976                               1   
7       0  26.000000  1.656320  111.933010                               1   
8       1  30.520854  1.784049  120.644178                               1   
9       1  25.523127  1.786532  114.534678                               1   

   FAVC      FCVC       NCP  CAEC  SMOKE      CH2O  SCC       FAF       TUE  \
0     1  3.000000  2.014671     2      0  1.292786    0  0.145687  0.000000   
1     1  2.000000  3.000000     2      0  3.000000    0  2.240500  0.000000   
2     1  3.000000  3.000000     2      0  1.063422    0  0.051097  0.543118   
3     1  3.000000  3.000000     2      0  1.005864    0  0.020060  0.695838   
4     1  3.000000  3.000000     2      0  2.863513    0  1.026452  0.714137   
5     1  2.777165  3.000000     2      0  2.106861    0  0.925941  0.291600   
6     1  2.233720  2.993634     2      0  2.028368    0  0.863158  0.449886   
7     1  3.000000  3.000000     2      0  2.774014    0  0.000000  0.138418   
8     1  2.499108  3.000000     2      0  2.040952    0  0.838739  0.489854   
9     1  2.100177  3.000000     2      0  2.099687    0  1.281165  0.247332   

   CALC  MTRANS  NObeyesdad  labels  
0     2       3           3       1  
1     3       3           2       1  
2     2       3           4       1  
3     2       3           4       1  
4     2       3           4       1  
5     2       0           3       1  
6     2       3           3       1  
7     2       3           4       1  
8     2       0           3       1  
9     2       3           3       1

In [128]:
pred2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 3, 1, 1, 3, 1, 3, 1, 1,
       1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1,
       1, 3, 3, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1,
       3, 1, 1, 1, 1, 3, 1, 1, 3, 3, 1, 1, 1, 3, 1, 1, 3, 1, 1, 3, 1, 1,
       3, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 3, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 3, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 0, 1, 1, 1,
       3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1,
       1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [125]:
df2['labels'].value_counts()

1    520
3     87
0      4
Name: labels, dtype: int64