In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

warnings.filterwarnings('ignore')

# Question a solution begins here
# Reading the data to be used to generate the clusters
df = pd.read_csv('Clustering_Data.csv')
df.head()

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       0  21.0    1.62    64.0                               1     0   2.0   
1       0  21.0    1.52    56.0                               1     0   3.0   
2       1  23.0    1.80    77.0                               1     0   2.0   
3       1  27.0    1.80    87.0                               0     0   3.0   
4       1  22.0    1.78    89.8                               0     0   2.0   

   NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  NObeyesdad  
0  3.0     2      0   2.0    0  0.0  1.0     3       3           1  
1  3.0     2      1   3.0    1  3.0  0.0     2       3           1  
2  3.0     2      0   2.0    0  2.0  1.0     1       3           1  
3  3.0     2      0   2.0    0  2.0  0.0     1       4           5  
4  1.0     2      0   2.0    0  0.0  0.0     2       3           6

In [3]:
df

Gender        Age    Height      Weight  family_history_with_overweight  \
0          0  21.000000  1.620000   64.000000                               1   
1          0  21.000000  1.520000   56.000000                               1   
2          1  23.000000  1.800000   77.000000                               1   
3          1  27.000000  1.800000   87.000000                               0   
4          1  22.000000  1.780000   89.800000                               0   
...      ...        ...       ...         ...                             ...   
1495       1  29.409825  1.801224  108.156190                               1   
1496       1  28.421533  1.829239  107.108190                               1   
1497       0  18.000000  1.692913   89.938890                               1   
1498       0  18.000000  1.668555   85.607466                               1   
1499       1  23.246702  1.652971   93.310284                               1   

      FAVC      FCVC       NCP  CAEC  SMOKE      CH2O  SCC       FAF  \
0        0  2.000000  3.000000     2      0  2.000000    0  0.000000   
1        0  3.000000  3.000000     2      1  3.000000    1  3.000000   
2        0  2.000000  3.000000     2      0  2.000000    0  2.000000   
3        0  3.000000  3.000000     2      0  2.000000    0  2.000000   
4        0  2.000000  1.000000     2      0  2.000000    0  0.000000   
...    ...       ...       ...   ...    ...       ...  ...       ...   
1495     1  2.385502  2.883984     2      0  2.140544    0  1.144876   
1496     1  2.465575  2.935381     2      0  2.480555    0  1.001830   
1497     1  2.818502  3.000000     2      0  1.991251    0  1.492967   
1498     1  2.081238  3.000000     2      0  1.183630    0  1.171770   
1499     1  1.368978  3.000000     2      0  1.953152    0  0.104707   

           TUE  CALC  MTRANS  NObeyesdad  
0     1.000000     3       3           1  
1     0.000000     2       3           1  
2     1.000000     1       3           1  
3     0.000000     1       4           5  
4     0.000000     2       3           6  
...        ...   ...     ...         ...  
1495  1.767468     2       0           2  
1496  1.670313     2       0           2  
1497  0.000000     3       3           2  
1498  0.000000     3       3           2  
1499  0.221830     3       0           2  

[1500 rows x 17 columns]

In [4]:
# performing scaling
scaler = StandardScaler()   
scaled_df = scaler.fit_transform(df)

# Creating 4 clusters (k=4)
kmeans = KMeans(n_clusters=4)

# Fit the model
kmeans.fit(scaled_df)

# Get the cluster centroids
print(kmeans.cluster_centers_)

[[ 0.5768554  -0.3478905   0.54619878  0.49761701  0.39394903  0.23878865
  -0.21082032  0.06400701  0.34087814 -0.08491685  0.3635843  -0.26148818
   0.10448858  0.21117601 -0.07882177  0.3258597   0.25279478]
 [-0.5045882  -0.42488688 -0.50068353 -0.65217175 -0.59323819 -0.64594783
   0.58602543  0.02243861 -0.35106931  0.14375736  0.06360119  3.82426464
   0.24617709 -0.09369374 -0.09175998  0.26182701 -0.11709896]
 [-0.12492832  1.67748019 -0.13281151  0.46234324  0.34706119  0.16433869
   0.11634355 -0.15310844  0.18367008  0.07803398 -0.11207783 -0.24668473
  -0.16759731 -0.58882076 -0.15958528 -1.69408496  0.4982579 ]
 [-0.64124664 -0.41181321 -0.59392436 -0.84598046 -0.64288119 -0.30421954
   0.11087754 -0.00481023 -0.52034836  0.04501205 -0.46210158 -0.26148818
  -0.09914648  0.06770218  0.2247168   0.48602732 -0.62900413]]


In [5]:
centroids = kmeans.cluster_centers_

In [6]:
centroids[3]

array([-0.64124664, -0.41181321, -0.59392436, -0.84598046, -0.64288119,
       -0.30421954,  0.11087754, -0.00481023, -0.52034836,  0.04501205,
       -0.46210158, -0.26148818, -0.09914648,  0.06770218,  0.2247168 ,
        0.48602732, -0.62900413])

In [7]:
print(kmeans.labels_)

[3 1 0 ... 0 3 2]


In [8]:
# Add the labels to the dataframe
df['labels'] = kmeans.labels_
df.head()

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       0  21.0    1.62    64.0                               1     0   2.0   
1       0  21.0    1.52    56.0                               1     0   3.0   
2       1  23.0    1.80    77.0                               1     0   2.0   
3       1  27.0    1.80    87.0                               0     0   3.0   
4       1  22.0    1.78    89.8                               0     0   2.0   

   NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  NObeyesdad  labels  
0  3.0     2      0   2.0    0  0.0  1.0     3       3           1       3  
1  3.0     2      1   3.0    1  3.0  0.0     2       3           1       1  
2  3.0     2      0   2.0    0  2.0  1.0     1       3           1       0  
3  3.0     2      0   2.0    0  2.0  0.0     1       4           5       0  
4  1.0     2      0   2.0    0  0.0  0.0     2       3           6       0

In [9]:
df2 = pd.read_csv('Classification_Data.csv')
df2.head(5)

Gender        Age    Height     Weight  family_history_with_overweight  \
0       1  24.481032  1.661277  90.744965                               1   
1       1  29.000000  1.641784  89.424947                               1   
2       1  27.968765  1.673767  89.995034                               1   
3       0  18.024744  1.617192  83.121811                               1   
4       0  18.106820  1.602129  82.412665                               1   

   FAVC      FCVC  NCP  CAEC  SMOKE      CH2O  SCC       FAF       TUE  CALC  \
0     1  1.712848  3.0     2      0  1.162153    0  0.458981  0.885532     3   
1     1  1.330700  3.0     2      0  1.880967    0  0.322013  0.000000     2   
2     1  1.961069  3.0     2      0  2.652327    0  0.569310  0.319008     2   
3     1  2.976509  3.0     2      0  1.022705    0  1.025690  0.313016     3   
4     1  2.319648  3.0     2      0  1.107164    0  0.692123  0.304020     3   

   MTRANS  NObeyesdad  
0       0           2  
1       0           2  
2       0           2  
3       3           2  
4       3           2

In [10]:
# Shuffle the dataset
df = df.sample(frac=1).reset_index(drop=True)
df.head(5)

Gender        Age    Height     Weight  family_history_with_overweight  \
0       0  26.000000  1.650000  63.000000                               0   
1       0  37.832949  1.610867  80.000000                               1   
2       1  18.118277  1.654757  80.000000                               1   
3       1  24.122589  1.856759  95.887056                               1   
4       0  27.000000  1.550000  63.000000                               0   

   FAVC      FCVC       NCP  CAEC  SMOKE      CH2O  SCC       FAF       TUE  \
0     1  3.000000  3.000000     2      0  1.000000    0  1.000000  0.000000   
1     1  2.036613  1.816980     2      0  1.930590    0  1.851404  0.000000   
2     1  2.821977  2.044035     2      0  1.954968    0  1.000000  0.854536   
3     1  1.116068  2.449067     2      0  2.000000    0  0.926350  1.971170   
4     1  2.000000  3.000000     2      0  1.000000    0  0.000000  1.000000   

   CALC  MTRANS  NObeyesdad  labels  
0     3       4           1       3  
1     2       0           2       2  
2     3       3           6       0  
3     2       3           6       0  
4     2       0           5       2

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

acc = 0

# train the model until the accuracy is greater than 0.9
while acc < 0.9:
    # generate a test size randomly to 2 decimal places
    rand = np.random.uniform(0.2, 0.3)
    rand = round(rand, 2)
    
    # Split the dataset into training and testing sets
    train, test = train_test_split(df, test_size=rand)
    
    # Create features and labels(targets)
    train_x = train.drop('labels', axis=1)
    train_y = train['labels']

    test_x = test.drop('labels', axis=1)
    test_y = test['labels']

    # create KNN classifier object
    knn_clf = KNeighborsClassifier(n_neighbors=7, metric='euclidean')

    # train the model(object) using the training sets
    knn_clf.fit(train_x, train_y)

    # predict the response for test dataset
    pred = knn_clf.predict(test_x)
    
    # Model Accuracy, how often is the classifier correct?
    acc = accuracy_score(test_y, pred)
print("Accuracy of the classifier:", acc)
print("Test size:", rand)

Accuracy of the classifier: 0.9121212121212121
Test size: 0.22


In [12]:
pred

array([0, 3, 0, 2, 0, 2, 2, 0, 3, 0, 0, 2, 0, 3, 3, 2, 3, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 2, 0, 0, 3, 2, 0, 2, 3, 2, 0, 0, 0, 3, 3, 0, 2,
       0, 3, 3, 0, 0, 0, 3, 2, 1, 2, 0, 0, 2, 3, 0, 3, 2, 0, 0, 3, 3, 3,
       0, 3, 3, 3, 0, 3, 0, 3, 0, 2, 3, 0, 2, 0, 3, 0, 0, 3, 2, 0, 0, 0,
       0, 3, 2, 3, 0, 0, 3, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 3, 0, 3,
       0, 3, 3, 0, 0, 3, 0, 3, 0, 2, 0, 1, 0, 2, 3, 0, 0, 3, 3, 0, 0, 0,
       2, 2, 2, 0, 3, 0, 0, 3, 2, 0, 2, 0, 1, 0, 2, 0, 2, 3, 3, 0, 3, 3,
       0, 1, 0, 3, 0, 3, 3, 0, 2, 2, 0, 2, 3, 0, 3, 1, 2, 0, 0, 0, 0, 0,
       3, 3, 3, 2, 0, 0, 3, 0, 0, 3, 0, 0, 3, 0, 3, 2, 0, 3, 3, 0, 2, 2,
       3, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 3, 0, 2, 0, 2,
       0, 2, 3, 3, 0, 0, 0, 0, 2, 3, 2, 3, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0,
       1, 3, 0, 0, 2, 0, 0, 3, 2, 3, 0, 0, 2, 0, 0, 2, 3, 2, 0, 0, 2, 3,
       3, 2, 0, 3, 0, 0, 3, 3, 3, 3, 2, 3, 3, 0, 2, 2, 0, 0, 2, 3, 0, 3,
       3, 2, 3, 0, 3, 3, 3, 0, 0, 2, 1, 0, 2, 3, 0,

In [13]:
# predict the response for df2 dataset
pred2 = knn_clf.predict(df2)

In [14]:
pred2.shape

(611,)

In [15]:
df2.shape

(611, 17)

In [16]:
# Add the labels to dataframe df2
df2['labels'] = pred2
df2.head(10)

Gender        Age    Height     Weight  family_history_with_overweight  \
0       1  24.481032  1.661277  90.744965                               1   
1       1  29.000000  1.641784  89.424947                               1   
2       1  27.968765  1.673767  89.995034                               1   
3       0  18.024744  1.617192  83.121811                               1   
4       0  18.106820  1.602129  82.412665                               1   
5       1  21.379676  1.701413  96.710735                               1   
6       1  21.353237  1.709731  95.032177                               1   
7       1  20.338815  1.698829  98.572753                               1   
8       1  20.720639  1.705304  99.873716                               1   
9       0  19.045357  1.612910  82.193405                               1   

   FAVC      FCVC       NCP  CAEC  SMOKE      CH2O  SCC       FAF       TUE  \
0     1  1.712848  3.000000     2      0  1.162153    0  0.458981  0.885532   
1     1  1.330700  3.000000     2      0  1.880967    0  0.322013  0.000000   
2     1  1.961069  3.000000     2      0  2.652327    0  0.569310  0.319008   
3     1  2.976509  3.000000     2      0  1.022705    0  1.025690  0.313016   
4     1  2.319648  3.000000     2      0  1.107164    0  0.692123  0.304020   
5     1  2.000000  2.961192     2      0  2.623344    0  0.981686  1.355370   
6     1  2.000000  2.973476     2      0  2.000000    0  0.000000  1.331527   
7     1  2.000000  2.392811     2      0  2.000000    0  0.000000  1.809310   
8     1  2.000000  1.293342     2      0  2.000000    0  0.000000  1.917679   
9     1  1.261288  2.930044     2      0  1.166655    0  0.133398  0.951740   

   CALC  MTRANS  NObeyesdad  labels  
0     3       0           2       2  
1     2       0           2       2  
2     2       0           2       2  
3     3       3           2       3  
4     3       3           2       3  
5     3       3           2       0  
6     3       3           2       0  
7     3       3           2       0  
8     3       3           2       0  
9     3       3           2       3

In [17]:
pred2

array([2, 2, 2, 3, 3, 0, 0, 0, 0, 3, 3, 0, 0, 2, 0, 2, 2, 0, 0, 0, 2, 0,
       2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0,
       0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 2, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0,
       0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0,
       0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 2, 0, 0,
       0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0,
       0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 0,
       0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0,
       0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 2,
       2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0,
       0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,

In [18]:
df2['labels'].value_counts()

0    463
2    144
3      4
Name: labels, dtype: int64